---
title: "class 05"
author: "zina dupal"
date: "2026-09-09"
output: 
  html_document:
    toc: true
    toc_float: true
    numbered_sections: true
    code_folding: show
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Game 01: Find your seat
```{r game01}
campus = jsonlite::fromJSON(
  "https://isa401-find-your-seat.vercel.app/campus.json")

dplyr::glimpse(campus)

fsb = campus[['Farmer']] # campus$Farmer; or campus[[5]]
fsb$code # step 1

sec_floor = fsb$floors[["2"]]
sec_floor$sections # step 2 
# or
# fsb$floors[[3]]$sections # using the position instead of the name of the list

df = sec_floor$rooms
df[6, 2] # step 3
# or 
# sec_floor$rooms
```

## Reading the excel file
```{r read_excel}
occupation = readxl::read_excel(
  path = "../data/occupation.xlsx", sheet = "Table 1.4", skip = 1
  )

# optional: clean the bottom 3 rows
occupation = occupation[-c(32, 33, 34), ] # delete 3 specific rows, keep all cols (since after the , is empty) --> 1:7
```

## JSON data
```{r json_data}
json_url = paste0(
  "https://data.cincinnati-oh.gov/",
  "resource/rvmt-pkmq.json?$limit=100")
crashes_json = jsonlite::fromJSON(json_url)

dplyr::glimpse(
  crashes_json[, c("crashdate", "dayofweek",
                   "crashseverity", "age")])
```

## Game 02: Importing data in R
```{r game02}
logins = readr::read_csv("../data/stage1.csv")
log = jsonlite::fromJSON("https://isa401-import-heist.vercel.app/api/stage2?key=smithj31")

stage2 = log$events

jsonlite::fromJSON("https://isa401-import-heist.vercel.app/api/finish?code=6")
```

