---
title: "Assignment 07"
author: "zina dupal"
date: "2026-10-05"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Q1

## Department info
```{r dept info}
departments <- c(
  "Accountancy",
  "Economics",
  "Entrepreneurship",
  "Finance",
  "Information Systems & Analytics",
  "Marketing",
  "Management"
)

base_url <- "https://miamioh.edu/fsb/directory/?up=/query/all/all/"

department_urls <- c(
  "Accountancy",
  "Economics",
  "Entrepreneurship",
  "Finance",
  "Information%20Systems%20--%20Analytics",
  "Marketing",
  "Management"
)

urls <- paste0(
  base_url,
  department_urls,
  "/all"
)

urls
```

## Test scrape: Accountancy
```{r scraping}
library(tidyverse)
library(rvest)

webpage <- read_html(urls[1])

names <- webpage |>
  html_elements("td strong a") |>
  html_node(xpath = "text()[1]") |>
  html_text2()

positions <- webpage |>
  html_elements("td i") |>
  html_text2()

websites <- webpage |>
  html_elements("td strong a") |>
  html_attr("href")

names
positions
websites
```

## Scraping departments
```{r scraping depts}
scrape_department <- function(url, department) {
  
  webpage <- read_html(url)
  
  names <- webpage |>
    html_elements("td strong a") |>
    html_node(xpath = "text()[1]") |>
    html_text2()
  
  positions <- webpage |>
    html_elements("td i") |>
    html_text2()
  
  websites <- webpage |>
    html_elements("td strong a") |>
    html_attr("href")
  
  tibble(
    department = department,
    name = names,
    position = positions,
    website = websites
  )
}

fsb_directory <- map2_dfr(
  urls,
  departments,
  scrape_department
)
```

## Results
```{r results}
head(fsb_directory)

unique(fsb_directory$department)
```

